dist: xenial
sudo: required
language: node_js
node_js:
  - "lts/*"

# safelist
branches:
  only:
    - production
    - staging

install:
  - wget "https://github.com/gohugoio/hugo/releases/download/v${HUGO_RELEASE}/hugo_extended_${HUGO_RELEASE}_Linux-64bit.deb"
  - sudo dpkg -i hugo*.deb
  - npm install postcss-cli
  - npm install autoprefixer

script:
  - if [ "$TRAVIS_BRANCH" = "production" ]; then export HUGO_BASEURL=$PROD_URL && cp themes/evictionlab/layouts/robots.prod.txt themes/evictionlab/layouts/robots.txt; fi
  - if [ "$TRAVIS_BRANCH" = "staging" ]; then export HUGO_BASEURL=$STAGING_URL; fi
  - hugo version # prints the Hugo version, just in case.
  - hugo # build the website

before_deploy:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin

deploy:
  - skip_cleanup: true
    provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: eviction-lab-website-staging
    region: us-east-1
    acl: public_read
    local_dir: public
    on:
      branch: staging
  - provider: script
    script: aws cloudfront create-invalidation --distribution-id=$CLOUDFRONT_ID_DEV --paths="/*"
    on:
      branch: staging
  - skip_cleanup: true
    provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: eviction-lab-website
    region: us-east-1
    acl: public_read
    local_dir: public
    on:
      branch: production
  - provider: script
    script: aws cloudfront create-invalidation --distribution-id=$CLOUDFRONT_ID_PROD --paths="/*"
    on:
      branch: production

env:
  global:
    - HUGO_RELEASE=0.69.2
