[build]
  publish = "public"
  command = "hugo"
  HUGO_VERSION = "0.69.2"

[context.deploy-preview]
  command = "hugo -D"
  HUGO_VERSION = "0.69.2"

[context.branch-deploy]
  command = "hugo -D"
  HUGO_VERSION = "0.69.2"
