baseURL = "/"

languageCode = "en-us"
title = "Eviction Lab Sandbox"
theme = "behave"

[[menu.updates]]
    name = "Events"
    weight = -80
    identifier = "about"
    url = "/updates/events/"
[[menu.updates]]
    name = "Research"
    weight = -90
    url = "/updates/research/"
[[menu.updates]]
    name = "Media"
    weight = -100
    url = "/updates/whats-new/media/"
[[menu.updates]]
    name = "Blog"
    weight = -110
    url = "/updates/whats-new/blog/"


[[menu.methods]]
    name = "Restricted Access Data"
    weight = -110
    url = "/methods/restricted-access-data/"


[[menu.maps_and_data]]
    name = "FTP Download Site"
    weight = -110
    url = "/maps-and-data/ftp-download-site/"


[[menu.learn_more_tell_your_story]]
    name = "Tell Us Your Story"
    weight = -110
    url = "/learn-more-tell-your-story/tell-us-your-story/"
[[menu.learn_more_tell_your_story]]
    name = "What Happens When You're Evicted"
    weight = -120
    url = "/learn-more-tell-your-story/what-happens-when-youre-evicted/"
[[menu.learn_more_tell_your_story]]
    name = "Audio Visual Stories"
    weight = -130
    url = "/learn-more-tell-your-story/audio-video-stories/"


[[menu.help_faq]]
    name = "Questions and Answers re: Site Use"
    weight = -110
    url = "/help-faq/questions-answers-site-use/"
[[menu.help_faq]]
    name = "Questions and Answers"
    weight = -120
    url = "/help-faq/questions-answers/"


[[menu.city_rankings]]
    name = "Mid-sized Cities/Counties"
    weight = -110
    url = "/city-rankings/midsized-cities-counties/"
[[menu.city_rankings]]
    name = "Top Cities"
    weight = -120
    url = "/city-rankings/top-cities/"


[[menu.about_us]]
    name = "Affiliations Funding"
    weight = -110
    url = "/about-us/affiliations-funding/"
[[menu.about_us]]
    name = "Book"
    weight = -120
    url = "/about-us/book/"
[[menu.about_us]]
    name = "Research Team Bios"
    weight = -130
    url = "/about-us/research-team-bios/"
[[menu.about_us]]
    name = "Web Team Bios"
    weight = -140
    url = "/about-us/web-team-bios/"
